name: Update Dependencies

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every Sunday at 00:00 UTC; adjust as desired
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pip-tools
        run: |
          pip install --upgrade pip
          pip install pip-tools

      - name: Compile dependencies
        id: compile_deps
        run: |
          pip-compile --upgrade requirements.in

      - name: Create or Update Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          author: "ParthivNaresh <parthivnaresh@gmail.com>"
          title: "Automated Latest Dependency Updates"
          body: "This is an auto-generated PR with the latest dependency updates."
          branch: "latest-dep-update"
          branch-suffix: "short-commit-hash"
          base: "main"
          add-paths: |
            requirements.txt
          assignees: "ParthivNaresh"

      - name: Auto-merge the PR
        if: steps.create_pr.outputs.pull-request-operation != 'none'
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = parseInt("${{ steps.create_pr.outputs.pr_number }}", 10);
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: "squash"
            });
            core.info(`Pull request #${prNumber} merged automatically.`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}